name: SBOM Generation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: AppThreat/cdxgen-action@v1
      with:
        output: "./reports/bom.xml"
        serverUrl: "https://deptrack.appthreat.io"
        apiKey: ${{ secrets.apiKey }}

    - uses: actions/upload-artifact@v1
      with:
        name: reports
        path: reports
