name: SBOM Generation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Generate BOM using cdxgen
      uses: appthreat/cdxgen-action@v1
      with:
        projectId: nil-cfg
        projectName: yaml
        projectVersion: 0.0.1
        output: "./reports/bom.xml"
    - uses: actions/upload-artifact@v1
      with:
        name: reports
        path: reports
