name: SBOM Generation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: AppThreat/cdxgen-action@v1
        with:
          projectId: nil-cfg
          projectName: Configify
          projectVersion: 0.0.1
