name: SBOM Generation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Generate BOM using cdxgen
      uses: appthreat/cdxgen-action@v1
      with:
        output: "./reports/bom.xml"
